2019-04-04 19:52:43.659 [error] <0.264.0> CRASH REPORT Process <0.264.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'spike_test' in vhost '/'">>}},{gen_server,call,[<0.276.0>,{subscribe,{'basic.consume',0,<<"spike_test">>,<<>>,false,false,false,false,[]},<0.278.0>},60000]}} in gen_server:call/3 line 223
2019-04-04 19:54:30.035 [error] <0.252.0>@Elixir.Spike.Queue.Producer:init:15 Supervisor 'Elixir.Spike.Supervisor' had child 'Elixir.Spike.Queue.Producer' started with 'Elixir.Spike.Queue.Producer':start_link([{queue_name,<<"spike_test">>}]) at undefined exit with reason no match of right hand value {ok,#{consumer_count => 0,message_count => 0,queue => <<"hello">>}} in 'Elixir.Spike.Queue.Producer':init/1 line 15 in context start_error
2019-04-04 19:55:02.021 [error] <0.264.0>@Elixir.Spike.Queue.Consumer:init:15 CRASH REPORT Process <0.264.0> with 0 neighbours crashed with reason: no match of right hand value {ok,#{consumer_count => 0,message_count => 0,queue => <<"spike_test">>}} in 'Elixir.Spike.Queue.Consumer':init/1 line 15
2019-04-04 19:55:10.141 [error] <0.247.0>@Elixir.Spike.Queue.Consumer:init:16 Supervisor 'Elixir.Spike.Supervisor' had child 'Elixir.Spike.Queue.Consumer' started with 'Elixir.Spike.Queue.Consumer':start_link([{queue_name,<<"spike_test">>}]) at undefined exit with reason no match of right hand value {ok,<<"amq.ctag-mWhgSjsbBbA4Alnhn1bfWQ">>} in 'Elixir.Spike.Queue.Consumer':init/1 line 16 in context start_error
2019-04-04 19:55:42.845 [error] <0.264.0>@Elixir.Spike.Queue.Consumer:handle_info:21 gen_server 'Elixir.Spike.Queue.Consumer' terminated with reason: no function clause matching 'Elixir.Spike.Queue.Consumer':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-8XDfe9KMWKkl2qzaLDmmHg">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 21
2019-04-04 19:55:42.873 [error] <0.264.0>@Elixir.Spike.Queue.Consumer:handle_info:21 CRASH REPORT Process 'Elixir.Spike.Queue.Consumer' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Spike.Queue.Consumer':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-8XDfe9KMWKkl2qzaLDmmHg">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 21
2019-04-04 19:55:42.874 [error] <0.247.0>@Elixir.Spike.Queue.Consumer:handle_info:21 Supervisor 'Elixir.Spike.Supervisor' had child 'Elixir.Spike.Queue.Consumer' started with 'Elixir.Spike.Queue.Consumer':start_link([{queue_name,<<"spike_test">>}]) at <0.264.0> exit with reason no function clause matching 'Elixir.Spike.Queue.Consumer':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-8XDfe9KMWKkl2qzaLDmmHg">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 21 in context child_terminated
2019-04-04 19:56:56.699 [error] <0.253.0> gen_server 'Elixir.Spike.Queue.Producer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Spike.Queue.Producer but no handle_call/3 clause was provided">>} in 'Elixir.Spike.Queue.Producer':handle_call/3 line 754
2019-04-04 19:56:56.705 [error] <0.253.0> CRASH REPORT Process 'Elixir.Spike.Queue.Producer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Spike.Queue.Producer but no handle_call/3 clause was provided">>} in 'Elixir.Spike.Queue.Producer':handle_call/3 line 754
2019-04-04 19:56:56.706 [error] <0.252.0> Supervisor 'Elixir.Spike.Supervisor' had child 'Elixir.Spike.Queue.Producer' started with 'Elixir.Spike.Queue.Producer':start_link([{queue_name,<<"spike_test">>}]) at <0.253.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Spike.Queue.Producer but no handle_call/3 clause was provided">>} in 'Elixir.Spike.Queue.Producer':handle_call/3 line 754 in context child_terminated
2019-04-04 21:46:29.544 [error] <0.269.0>@Elixir.AMQP.Queue:bind CRASH REPORT Process <0.269.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.AMQP.Queue':bind(#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.272.0>},...}, <<"spike_test">>)
2019-04-04 21:49:39.795 [error] <0.269.0> gen_server 'Elixir.Spike.Queue.Consumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{something => <<"else">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-04-04 21:49:39.800 [error] <0.269.0> CRASH REPORT Process 'Elixir.Spike.Queue.Consumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{something => <<"else">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-04-04 21:49:39.800 [error] <0.252.0> Supervisor 'Elixir.Spike.Supervisor' had child 'Elixir.Spike.Queue.Consumer' started with 'Elixir.Spike.Queue.Consumer':start_link([{queue_name,<<"spike_test">>}]) at <0.269.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{something => <<"else">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
